# Generated by Django 4.2.19 on 2025-03-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0002_rename_eatery_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
