# Generated by Django 4.2.19 on 2025-03-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine',
            name='features',
            field=models.TextField(default='No features listed', max_length=100),
        ),
    ]
