# Generated by Django 4.2.19 on 2025-03-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0005_dine_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dine_images/'),
        ),
        migrations.AlterField(
            model_name='dine',
            name='features',
            field=models.TextField(default='No features available', max_length=100),
        ),
    ]
