# Generated by Django 4.2.19 on 2025-03-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0006_dine_image_alter_dine_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dine',
            name='image',
            field=models.ImageField(default='dine_images/default.jpg', upload_to='dine_images/'),
        ),
    ]
