# Generated by Django 4.2.19 on 2025-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0007_alter_dine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dine_images/'),
        ),
    ]
