# Generated by Django 4.2.19 on 2025-03-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0008_alter_dine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dine',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='dine_images/'),
        ),
    ]
