# Generated by Django 4.2.19 on 2025-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(default='No features available', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dine_images/')),
            ],
        ),
    ]
