# Generated by Django 4.2.19 on 2025-03-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_attraction_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='activity_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='activity_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='dine_images/'),
        ),
    ]
