# Generated by Django 4.2.19 on 2025-03-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_attraction_activity_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='activity_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
