# Generated by Django 4.2.19 on 2025-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
