# Generated by Django 4.2.19 on 2025-03-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='description_one',
            field=models.TextField(blank=True, null=True),
        ),
    ]
